export const COU_CODE_TO_CURRENCY: Record<string, string> = {
  AFG: "AFN",
  DZA: "DZD",
  AUS: "AUD",
  AZE: "AZN",
  BHR: "BHD",
  BGD: "BDT",
  BLR: "BYN",
  BRA: "BRL",
  BGR: "BGN",
  KHM: "KHR",
  CMR: "XAF",
  CAN: "CAD",
  CHN: "CNY",
  COD: "CDF",
  CZE: "CZK",
  EGY: "EGP",
  EST: "EUR",
  ETH: "ETB",
  FIN: "EUR",
  FRA: "EUR",
  DEU: "EUR",
  GRC: "EUR",
  HKG: "HKD",
  HUN: "HUF",
  IND: "INR",
  IDN: "IDR",
  ITA: "EUR",
  JPN: "JPY",
  KEN: "KES",
  KWT: "KWD",
  LVA: "EUR",
  LTU: "EUR",
  MDG: "MGA",
  MWI: "MWK",
  MYS: "MYR",
  MDA: "MDL",
  MAR: "MAD",
  NPL: "NPR",
  NLD: "EUR",
  NGA: "NGN",
  PAK: "PKR",
  PHL: "PHP",
  POL: "PLN",
  ROU: "RON",
  RUS: "RUB",
  SEN: "XOF",
  SGP: "SGD",
  SVK: "EUR",
  ZAF: "ZAR",
  ESP: "EUR",
  LKA: "LKR",
  SWE: "SEK",
  CHE: "CHF",
  TZA: "TZS",
  THA: "THB",
  UKR: "UAH",
  ARE: "AED",
  GBR: "GBP",
  USA: "USD",
  ZMB: "ZMW",
  SSD: "SSP",
  UGA: "UGX",
  BEL: "EUR",
  CYP: "EUR",
  DNK: "DKK",
  IRL: "EUR",
  LUX: "EUR",
  NOR: "NOK",
  PRT: "EUR",
  SOM: "SOS",
  LBN: "LBP",
  ERI: "ERN",
  QAT: "QAR",
  BEN: "XOF",
  BMU: "BMD",
  BFA: "XOF",
  BDI: "BIF",
  COG: "XAF",
  GEO: "GEL",
  GHA: "GHS",
  CIV: "XOF",
  KAZ: "KZT",
  KGZ: "KGS",
  LBR: "LRD",
  MLT: "EUR",
  MTQ: "EUR",
  MCO: "EUR",
  NAM: "NAD",
  NZL: "NZD",
  NER: "XOF",
  RWA: "RWF",
  SMR: "EUR",
  SLE: "SLE",
  SVN: "EUR",
  TJK: "TJS",
  UZB: "UZS",
  VNM: "VND",
  ZWE: "ZWL",
  ALB: "ALL",
  AND: "EUR",
  ARM: "AMD",
  AUT: "EUR",
  BIH: "BAM",
  HRV: "EUR",
  ISL: "ISK",
  LIE: "CHF",
  MNE: "EUR",
  MKD: "MKD",
  SRB: "RSD",
  VAT: "EUR",
};

export function legalCurrencyForCouCode(couCode: string): string {
  const a3 = couCode?.trim().toUpperCase();
  if (!a3) return "USD";
  return COU_CODE_TO_CURRENCY[a3] ?? "USD";
}

export type PlatformCurrencyOption = {
  couCode: string;
  couName: string;
  currencyCode: string;
};

export function toPlatformCurrencyOptions(
  countries: { couCode: string; couName: string }[],
): PlatformCurrencyOption[] {
  return countries
    .map((c) => ({
      couCode: c.couCode.toUpperCase(),
      couName: c.couName,
      currencyCode: legalCurrencyForCouCode(c.couCode),
    }))
    .sort((a, b) => a.currencyCode.localeCompare(b.currencyCode));
}
